services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-gitops
    environment:
      POSTGRES_USER: krishna
      POSTGRES_PASSWORD: 1729
      POSTGRES_DB: postgresdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: backend-gitops:v1
    container_name: backend-gitops
    env_file:
      - backend/.env
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  frontend:
    image: frontend-gitops:v1
    container_name: frontend-gitops
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  pgdata:
